### ISSUE TITLE
More use examples please!

### ISSUE THREAD

**Issue by Sheffyp** [andreek/node-eibd#13]
Hi Andree and co.

I am trying to build a home automation system using node and eibd. However I am really struggling to implement eibd. Specifically could you demo how to make a simple groupswrite request to the knx bus via  node and eibd? I have a working implementation of eibd running on my machine and I can commandline a functioning groupswrite request on the CLI. I just cant implement via node.  Sorry this is such a noob question - but I am using the opportunity to build the system to learn node and the mean stack. Thank you for your work with eibd - it looks great (even better if i could use it!)

Thanks

Mark

**Comment by andreek** [comment]
There are some examples in the bin folder. I think that's what you're searching for.

https://github.com/andreek/node-eibd/tree/master/bin
