### ISSUE TITLE
macosx

### ISSUE THREAD

**Issue by petkoe** [andreek/node-eibd#14]
Hi, has anybody tried this on macosx? what are the dependencies? thanks peter

**Comment by stefano055415** [comment]
hello , I get this error "RangeError: Maximum call stack size exceeded"

**Comment by andreek** [comment]
Can you may give some more details?

**Comment by stefano055415** [comment]
I tried to connect to my router IP / KNX with your example,

var eibd = require('eibd');
/**
 * groupsocketlisten
 */
function groupsocketlisten(opts, callback) {

  var conn = eibd.Connection();

  conn.socketRemote(opts, function(e) {
	  conn.openGroupSocket(0, callback);
  });

}

var host = '192.168.1.90';
var port = 3671;

groupsocketlisten({ host: host, port: port }, function(parser) {

  parser.on('write', function(src, dest, dpt, val){
    console.log('Write from '+src+' to '+dest+': '+val);
  });

  parser.on('response', function(src, dest, val) {
    console.log('Response from '+src+' to '+dest+': '+val);
  });

  parser.on('read', function(src, dest) {
    console.log('Read from '+src+' to '+dest);
  });

});

 the connection answer timeout

**Comment by stefano055415** [comment]
I think the problem is that I use a router and not a gateway IP / KNX .
I have create a connection with Java and properly communicate

**Comment by andreek** [comment]
Well,.. this library is only a client for eib daemon. You can't connect to a knx router or gateway. I think you need to install eib/knx daemon. 

See https://github.com/knxd/knxd
