### ISSUE TITLE
Error when running example code

### ISSUE THREAD

**Issue by cjk** [andreek/node-eibd#17]
When I download the library and try to run the example-code provided in the Readme, I get:

```
(null):0
(null)

RangeError: Maximum call stack size exceeded
```

I'm using node 0.12.7

Not sure what I'm doing wrong, any pointers?

**Comment by snowdd1** [comment]
What exactly did you try?
The example at the end of the readme in which a groupsocketlisten() is shown?
Did you change the IP and port to match your knxd/eibd server (default in the example is localhost:6720)
What Hardware and OS are you using?
I am using node-eibd successfully on node 0.12.1 on arm7 (raspberry2).

**Comment by cjk** [comment]
@snowdd1 Thanks for the quick reply.
I was trying out the example on the bottom using `groupsocketlisten()`.

I was probably using the wrong connection-values (port, ip-address), will have to try this again. But from the error-message I did not think of a connection-error at first. It sounded like perhaps the event-emitter implentation was causing problems.

`./bin/groupread localhost 3671 "1/1/5"` was also giving me

```
(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
[...]
RangeError: Maximum call stack size exceeded
```

for the same reasons.

Thanks for letting me know to check my eibd-connection first!

**Comment by cjk** [comment]
OK, after starting eibd with the `-i` option (listen on TCP) instead of `-u` it's working without the error.

Now I just have to figure out how to listen to ongoing bus-traffic, since that doesn't seem to work with the `-i` option.

**Comment by snowdd1** [comment]
It's running with -i in my installation. Listen on the bus - have a look at my pull request #15. I have implemented a very basic subscription model with callbacks that can be used to subscribe to specific group addresses. E.g. if you want your nodeJS program function to be called if 1/1/5 is sent over the wire.

**Comment by cjk** [comment]
@snowdd1 Great advice! I looked at your fork and considering using that one instead (perhaps you should publish it on NPM using your namespace).
While I'm at it, perhaps I should replace eibd with knxd along the way, it seems to work for most people who have tried it. I'll see if I can create an Arch-Package and publish it then for others to re-use.

**Comment by snowdd1** [comment]
I just did a commodity function I needed myself. @andreek is clearly the owner of this whole thing.
If he is not looking into github for some weeks, I might package the extension into an eibd-commodity package myself.

**Comment by snowdd1** [comment]
> Thanks for letting me know to check my eibd-connection first!
Been there myself, anyway...

**Comment by cjk** [comment]
Somewhat OT here, but people may find it useful:
I created a package-build for Arch-Linux for the KNXd that can be used as a (maintained) drop-in replacement for EIBd - works for me so far: https://aur.archlinux.org/packages/knxd-git/

**Comment by andreek** [comment]
@cjk I guess '-u' is used in eibd/knxd for usb interface, right? Maybe we have to write this in the README. node-eibd only supports TCP.

**Comment by cjk** [comment]
@andreek You're right, I actually don't need `-u` since I'm not using USB (have an IP-router). So, node-eibd is the perfect library for me, thanks for writing it! :+1: 
But it's also true that documentation is a bit scarce right now, which makes it hard for beginners to get up-and-running. Lot's of trial-and-error needed.
Let's see if we can improve the docs in the future, I'll try to help if I can.
