### ISSUE TITLE
command line apps have no error handlers

### ISSUE THREAD

**Issue by snowdd1** [andreek/node-eibd#23]
Hi André,
the command line apps (which usually serve as great examples) have no error handlers for connection.openGroupSocket() and socketRemote(). If IP or port of knxd/eibd are wrong they fail with a cryptic error message.
I stumbled across that as I used that code in my [homebridge-knx](https://github.com/snowdd1/homebridge-knx/issues/13) homekit integration, and users wondered what the strange error message:
**(node) warning: possible EventEmitter memory leak detected. 11 data listeners added. Use emitter.setMaxListeners() to increase limit.** was about. It should have shouted at them *Set your IP and Port numbers for knxd/eibd right!*

Do you consider putting an `err` variable and an 'if' statement into it?
Regards
Raoul

**Comment by snowdd1** [comment]
I just tested that with an example: https://github.com/snowdd1/node-eibd/commit/45408f89c87a5caa87e271211397df5fc3250464
Seems to work.

**Comment by andreek** [comment]
Thank you for reporting!

**Comment by snowdd1** [comment]
Cool, thanks!
