### ISSUE TITLE
Documentation link dead

### ISSUE THREAD

**Issue by LouisonGitzinger** [andreek/node-eibd#28]
I'm trying to build a KNX listener with Node based on your framework. 
Is it possible to reUp the documentation pdf in order to better understand node-eibd ?
Thank in advance

Louison

**Comment by andreek** [comment]
The documentation pdf describes the eibd protocol and was not part of this project. Doesn't think that would help you.. but thanks for reminding it is offline. Documents a todo anyway for this project.

I think you need to take a look at groupsocketlisten in the bin path. It's listening on everything happening on the eibd/knx bus.

**Comment by LouisonGitzinger** [comment]
Thank you !
