### ISSUE TITLE
knx connection

### ISSUE THREAD

**Issue by reejinbouk** [andreek/node-eibd#32]
Hi
I', trying to connect to HDL M/IPRT.1 knx router
It use 3671 port in ETS
my code is:
var eibd = require('eibd');
var opts = {
  host: "192.168.10.41",
  port: 3671
};

function groupsocketlisten(opts, callback) {
  var conn = eibd.Connection();
  conn.socketRemote(opts, function(err) {
		if (err) {
			// a fatal error occurred
			console.log(err);
			throw new Error("Cannot reach knxd or eibd service, please check installation and config.json");
		}
		conn.openGroupSocket(0, callback);
	});
}

groupsocketlisten(opts, function(parser) {
  parser.on('write', function(src, dest, dpt, val){
    console.log('Write from '+src+' to '+dest+': '+val);
  });
  parser.on('response', function(src, dest, val) {
    console.log('Response from '+src+' to '+dest+': '+val);
  });
  parser.on('read', function(src, dest) {
    console.log('Read from '+src+' to '+dest);
  });
});

Try 6720 and 3671 ports in node-eibd, but get this error:

{ [Error: connect ECONNREFUSED 192.168.10.41:3671]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '192.168.10.41',
  port: 3671 }
/home/roman/Project/knx.js:13
			throw new Error("Cannot reach knxd or eibd service, please check installation and config.json");
			^

Error: Cannot reach knxd or eibd service, please check installation and config.json
    at Socket.<anonymous> (/home/roman/Project/knx.js:13:10)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1253:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

How to solvr this error? 
TY

**Comment by snowdd1** [comment]
Hi, 
It's Roman, I guess? 
You've obviously glued some pieces of code together without reading the complete README of node-eibd first.

**node-eibd** can **only** connect to an **eibd** or **knxd** server, not to any other knx router. If you want to use node-eibd, you need to get a knxd server running (and yes, you can connect this one to most of the knx-IP-routers - see there)

Regards

**Comment by reejinbouk** [comment]
Hi,
You guess )
tell me , please, eibd/knxd server - is it hardware or software.
can you give some links for this server?
thank you

**Comment by reejinbouk** [comment]
i'm compile and install knxd (https://github.com/knxd/knxd) and it connect to knx

**Comment by reejinbouk** [comment]
which opts should i start the knxd if i get this configuration:
debian + openhab (with knx binding) + knxd +KNX IP ROUTER

should i use tunelling or multicast?
thank you

**Comment by snowdd1** [comment]
Hi Roman, 
I assume your KNX router is using multicast itself, so that is taken and you can use knxd to connect to that.

After failing with knxd I wrote a wiki page dealing with the options:
https://github.com/knxd/knxd/wiki/Command-line-parameters

You probably need the following:

--trace=1023
--error=9
(for debugging)

--eibaddr=1.1.1 (or other free address that fits into your line)

--listen-tcp=6720
--listen-local=/tmp/eib
(to connect to your knxd, use the ip of the knxd and port 6720, or locally a unix socket named /tmp/eib)


--layer2=ip:
(to connect to your KNX router via multicast address)

Good luck!
Raoul
