### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by rnenjoy** [andreek/node-eibd#34]
Thanks for a great project!

I'm having trouble connecting to my KNX ABB Router. It has IP 192.168.0.100 and i think default port is 3671.

node groupread 192.168.0.100 3671 2/2/60 1
[ERROR]Error: connect ECONNREFUSED 192.168.0.100:3671

Any ideas? Have i missunderstood something?

**Comment by andreek** [comment]
You need to have knxd or eibd installed. This library can communicate with these daemons not with knx devices.

We have to update documentation asap. You aren't the only one who has this question.

**Comment by rnenjoy** [comment]
Ok thanks alot for the help! :) My guess is that knxd is the one you prefer? I'll try that one! Thanks for a great work on this!!

**Comment by andreek** [comment]
Yes. Its a fork of eibd.
