### ISSUE TITLE
Missing DPT in telegram

### ISSUE THREAD

**Issue by pakerfeldt** [andreek/node-eibd#35]
Is it true that each telegram contains the DPT the value is encoded in? I have a hardware that sends telegram that I want to read in node-red (using a plugin that uses node-eibd). However, the value turns out being undefined/null and it claims the telegram is in DPT1 (when it should be DPT9 4 byte FP). 

When I look in ETS5, the telegram does not have a DPT specified and the value is shown in raw format.

If it's true that DPT should be included in the telegram then the hardware doesn't seem to do the right thing. However, is there any way to work around that? Like specifying what DPT the value should be intepreted as?

**Comment by andreek** [comment]
The telegram does not have the information about the DPT value. 

To get a workaround we are doing assumptions and try to identify via package length the right dpt. See https://github.com/andreek/node-eibd/blob/master/lib/decoder.js#L178

**Comment by pakerfeldt** [comment]
Okay, interesting. Thanks for the clarification.
