### ISSUE TITLE
When sending a read message, the response contains the wrong value

### ISSUE THREAD

**Issue by FloMaetschke** [andreek/node-eibd#37]
The lamp (test object) is off. I try to read its status group address.
I tried using the ETS5 and i receive the correct status (on or off) with DPT1.001 (DPT1).
When using this lib it always results in 0, but not 1 for on when the lamp is on.

**Comment by snowdd1** [comment]
@FloMaetschke  
Can you send some more details? It seems that no one else is observing this behaviour, so it might be important to understand your setup.

**Comment by andreek** [comment]
I’m closing this issue because it has been inactive for a few months. 

Please reopen if you still encounter this issue.

Thank you!
