### ISSUE TITLE
16 bit group addresses

### ISSUE THREAD

**Issue by snowdd1** [andreek/node-eibd#40]
Hi all,
I just found out that address translations in lib/tools.js support 31/7/255 in [line 22](https://github.com/andreek/node-eibd/blob/master/lib/tools.js#L22) but only 15/7/255 in [line 38](https://github.com/andreek/node-eibd/blob/master/lib/tools.js#L38) - is that a glitch or was that done on purpose?  

Once the address is using 0xf and once 0x1f.

Best regards
Raoul

**Comment by snowdd1** [comment]
Just created PR #41

**Comment by andreek** [comment]
Should be a glitch. I'll merge PRs later this week.

**Comment by snowdd1** [comment]
Cool, thanks.

**Comment by MrWichtig** [comment]
Super!  d.h.: es gibt wieder Hoffnung die GA's bis 31/x/x verwenden zu können :-)
