### ISSUE TITLE
groupread executable broken for non-socket reads

### ISSUE THREAD

**Issue by cjk** [andreek/node-eibd#45]
Looks like when introducing the --socket parameter into ./bin/ executables at least groupread got broken by checking for optional variable `value` which is only used for socket-calls.

Thus, something like
```
node ./node_modules/eibd/bin/groupread somehost 6720 "1/4/2"
```
... will always fail, since the value-parameter is for sockets only.

Actually, `value` is never set in the code so will always be `undefined`.

**Comment by snowdd1** [comment]
I thought I had checked all of them, but of course I will look into it, as I created the PR for the sockets.

**Comment by andreek** [comment]
FYI: I'll wait for this issue before publishing next version to npm.

**Comment by snowdd1** [comment]
Ok, copy-and-paste error: the **value** field does not belong anywhere in group**read** and must not be validated. Does not belong to **--socket** either.

**Comment by andreek** [comment]
Thank you @snowdd1, really quick. I'll publish in the evening today.

**Comment by cjk** [comment]
Yep, that was fast - awesome work, thanks folks! :1st_place_medal:
