### ISSUE TITLE
npm install eibd could't set

### ISSUE THREAD

**Issue by wuhanwang** [andreek/node-eibd#51]
when I execute "npm install eibd",it's display 
`
npm@3.10.9 /usr/local/bin/node-v7.1.0-linux-armv7l/lib/node_moudles/npm

|___ eibd@0.3.9
`

**Comment by andreek** [comment]
I don't see an issue. Its standard npm output. Do you run into any issue using eibd after ```npm install```?

**Comment by wuhanwang** [comment]
I knowd it now,it means it installd in the director  /usr/local/bin/node-v7.1.0-linux-armv7l/lib/node_moudles/npm.
