### ISSUE TITLE
trouble getting groupread response

### ISSUE THREAD

**Issue by OmarReg** [andreek/node-eibd#59]
As you indicate in the readme the groupread function does not wait for an answer. Why is that and is there another way to recover the answer in the function's callback?

**Comment by snowdd1** [comment]
You could write a wrapper yourself, if you really want to kind-of-wait for the answer. General approach:

create a group listener;
create a function that 
- listens to the incoming messages (or hooks itself to the fitting event)
- has timer to stop waiting after a while ("timeout")
send out the read request.
