### ISSUE TITLE
RangeError (buffer.js)

### ISSUE THREAD

**Issue by koenbroumels** [andreek/node-eibd#6]
i am trying to run groupsocketlisten see below but i get this RangeError. 
I have run it before but i lost my "code", are you able to assist or is it all out-of-your-league because i read your comment on the enhancement request. 

C:\node_modules\.bin>groupsocketlisten 10.0.0.11 3671

buffer.js:176
        this.length = +subject > 0 ? Math.ceil(subject) : 0;
                                          ^
RangeError: Maximum call stack size exceeded

C:\node_modules\.bin>

**Comment by shacal** [comment]
3671 -> default KNX gateway port, so accessing direct KNX/IP gateway/router...
