### ISSUE TITLE
Connection.end() calls Parser.end(), which does not exist

### ISSUE THREAD

**Issue by owagner** [andreek/node-eibd#7]
Calling Connection.end() calls Parser.end(), which does not exist, causing an Exception:

TypeError: Object #<Parser> has no method 'end'
    at Connection.end (/opt/iobroker/adapter/knx/node_modules/eibd/lib/connection.js:57:17)

**Comment by Sheffyp** [comment]
Hey Andree, 

I'm getting the same error - do you have any idea why it's getting called? And what I might do about it?

Thanks

Mark

**Comment by Sheffyp** [comment]
Sorry was using node -red - now updated consider resoled
